### ISSUE TITLE
dependency ctk auto install still not working

### ISSUE THREAD

**Issue by salkin-mada** [madskjeldgaard/Particular#2]
evaluate
`Quarks.install("https://github.com/madskjeldgaard/Particular.git");`

post window throws:
```
Installing Particular
ERROR: Cannot parse dependency: Ctk Quark: Particular[1.0]
WARNING: Ctk not found
Adding path: /Users/someUser/Library/Application Support/SuperCollider/downloaded-quarks/Particular
Particular installed
-> Quark: Particular[1.0]
```

**Comment by madskjeldgaard** [comment]
ohlala, that's strange. Maybe there's a typo. Let me check. Also, maybe we should actually remove the CTK stuff entirely from this project

**Comment by madskjeldgaard** [comment]
Okay, the problem was the dependencies were in single quotes and should be in double quotes
